### ISSUE TITLE
[1.8] NullPointerException on Load

### ISSUE THREAD

**Issue by OhBlihv** [np98765/BattleKits#16]
CraftBukkit version: 1.4.5 Beta 0.2 
Plugin list: BattleKits
BattleKits version: 1.8 (BukkitDev pre-approved file)
Config file link (pastebin.com): Does not make/load a config  
Server log link (pastebin.com): Ill just paste it here (the error of course)

2012-12-07 23:01:54 [SEVERE] Could not load 'plugins\BattleKits (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:152)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:227)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:205)
    at net.minecraft.server.ServerConfigurationManagerAbstract.<init>(ServerConfigurationManagerAbstract.java:51)
    at net.minecraft.server.ServerConfigurationManager.<init>(SourceFile:11)
    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:398)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
    at com.lavacraftserver.BattleKits.BattleKits.<init>(BattleKits.java:28)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:148)
    ... 9 more

When does the error occur? Startup

Steps to reproduce error: Run Server?

Any other relevant info:
The " (2).jar" suffix does not change its startup state.
With or without, it does not load.

**Comment by lol768** [comment]
Cheers for the informative report, I'll look into it

**Comment by lol768** [comment]
Right, figured out the issue.

**Comment by lol768** [comment]
Fixed http://199.241.30.86:2020/job/BattleKits/1585/
https://github.com/np98765/BattleKits/commit/95c81b1839e3592ac2cff55d06ccf0bc0aed85a5

Re-open if the issue persists :)
