### ISSUE TITLE
UnsupportedClassVersionError from saksham12345omfg

### ISSUE THREAD

**Issue by lol768** [np98765/BattleKits#55]
**Autogenerated issue from http://dev.bukkit.org/server-mods/battlekits/?comment=413 (author: saksham12345omfg) at Jan 01, 2013 at 17:29 UTC**

Caused by: java.lang.UnsupportedClassVersionError: com/lavacraftserver/BattleKits/BattleKits : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
    ... 14 more
keep getting this error in my console?

**Comment by lol768** [comment]
You **need** Java 7 to use this plugin. Java 6 is outdated, and very soon will not be getting any security updates at all.. I do not use Java 6 to compile my plugins at present.
