### ISSUE TITLE
Once per life?

### ISSUE THREAD

**Issue by ghost** [np98765/BattleKits#96]
Hello I have an issue, when i try and get my kit it says i can only use it once per life, but i've already died like 3 time and didnt use a kit.
here is my config.yml : http://pastebin.com/8jMgAx6a

**Comment by lol768** [comment]
Looks like there's some remnants of previous versions of battlekits in that file, mainly restriction stuff. Mind completely regenerating it for me?

**Comment by ghost** [comment]
Can you please list the things that can be included (set to true/false) in the settings part of the config?
thnx

**Comment by lol768** [comment]
Either regenerate the config or look at the example config in the repository. There are no other hidden settings.

**Comment by ghost** [comment]
I regenerated my folder, still the same thing. As soon as i respawn i says that i can only use one kit per life, also i get this error when i try and do /kit [kitname]:

2013-02-14 17:44:10 [SEVERE] Could not pass event PlayerDeathEvent to BattleKits v2.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
at org.bukkit.craftbukkit.v1_4_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:332)
at net.minecraft.server.v1_4_R1.EntityPlayer.die(EntityPlayer.java:256)
at net.minecraft.server.v1_4_R1.EntityLiving.damageEntity(EntityLiving.java:758)
at net.minecraft.server.v1_4_R1.EntityHuman.damageEntity(EntityHuman.java:616)
at net.minecraft.server.v1_4_R1.EntityPlayer.damageEntity(EntityPlayer.java:309)
at net.minecraft.server.v1_4_R1.EntityLiving.a(EntityLiving.java:957)
at net.minecraft.server.v1_4_R1.EntityHuman.a(EntityHuman.java:1217)
at net.minecraft.server.v1_4_R1.Entity.a(Entity.java:778)
at net.minecraft.server.v1_4_R1.EntityLiving.a(EntityLiving.java:237)
at net.minecraft.server.v1_4_R1.EntityPlayer.b(EntityPlayer.java:413)
at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:428)
at net.minecraft.server.v1_4_R1.Packet10Flying.handle(SourceFile:136)
at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:113)
at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:30)
at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598)
at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NullPointerException
at com.lavacraftserver.BattleKits.DeathEvent.onPlayerDeath(DeathEvent.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)

**Comment by lol768** [comment]
Can I have all three config files pastebinned please?

**Comment by ghost** [comment]
http://pastebin.com/XdJWPkuQ
http://pastebin.com/vTHavBWg
http://pastebin.com/kkNAcYdE

**Comment by lol768** [comment]
When  you say config.yml, do you mean global.yml?

**Comment by ghost** [comment]
yes

**Comment by lol768** [comment]
Aware of why this is happening.. Please wait for a fix

**Comment by ghost** [comment]
How, long will I have to wait? Also, for some people it works fine, maybe you can give me like the working files (in pastebin) and then i just switch with the ones i have now.

**Comment by lol768** [comment]
Updated on DBO - awaiting approval

**Comment by ghost** [comment]
I'm trying to do the global.yml but i dont know what some methods/booleans are:
-  no-auto-update: false
-  override-disable-respawn-kits: true
-  clear-default: false

I dont know when they do, please can you explain?
Thnx

**Comment by lol768** [comment]
The first one doesn't exist, the second one basically disables automatically giving out kits and the last one specifies whether to clear the inventory between kit changes - this shouldn't be necessary and is a workaround for a problem fixed in 2.0.2.

**Comment by ghost** [comment]
Also there is this error:
2013-02-17 19:11:19 [SEVERE] Error occurred while disabling BattleKits v2.0.2 (Is it up to date?)
java.lang.NullPointerException
at com.lavacraftserver.BattleKits.BattleKits.onDisable(BattleKits.java:173)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:434)
at org.bukkit.craftbukkit.v1_4_R1.CraftServer.reload(CraftServer.java:566)
at org.bukkit.Bukkit.reload(Bukkit.java:184)
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:514)
at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchServerCommand(CraftServer.java:506)
at net.minecraft.server.v1_4_R1.DedicatedServer.al(DedicatedServer.java:260)
at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:225)
at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)

it only apears when i reload/stop the server.

**Comment by lol768** [comment]
Sorry :cry:, this is part of the same issue. Will be fixed shortly

**Comment by ghost** [comment]
its fine :D

**Comment by ghost** [comment]
I have a problem with breaking and placing blocks :(
Global <--- http://pastebin.com/DUtkuQ8W
Kit <--- http://pastebin.com/qfZDUe9c

XPerms: 
Permissions <--- http://pastebin.com/ifsUaHjj

When a person is in the group Builder, he can place but not break blocks. When i OP them they can... but i dont want that, i just want for them to break and place blocks without OP, just permissions.

**Comment by lol768** [comment]
Set enable restrictions to false if you don't want to mess with permissions :-)

**Comment by ghost** [comment]
I want the rank Member
-Not to drop items
-Not to pick items up
-Not to break blocks
-Not to place blocks
But i want the rank Builder:
-To place
-To break blocks
-Not to drop items
-Not to pick items up

**Comment by lol768** [comment]
Then you'll need to use permissions.

Closing due to inactivity.
