### ISSUE TITLE
Error reports

### ISSUE THREAD

**Issue by xron89** [np98765/BattleKits#99]
Not sure if you wanted this just letting you know - 

2013-02-14 23:10:24 [SEVERE] Could not pass event PlayerDeathEvent to BattleKits v2.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
at org.bukkit.craftbukkit.v1_4_6.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:330)
at net.minecraft.server.v1_4_6.EntityPlayer.die(EntityPlayer.java:255)
at org.bukkit.craftbukkit.v1_4_6.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:71)
at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:44)
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:102)
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:96)
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:380)
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:299)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
at org.bukkit.craftbukkit.v1_4_6.CraftServer.dispatchCommand(CraftServer.java:510)
at net.minecraft.server.v1_4_6.PlayerConnection.handleCommand(PlayerConnection.java:979)
at net.minecraft.server.v1_4_6.PlayerConnection.chat(PlayerConnection.java:897)
at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:852)
at net.minecraft.server.v1_4_6.Packet3Chat.handle(Packet3Chat.java:44)
at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:290)
at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:112)
at net.minecraft.server.v1_4_6.ServerConnection.b(SourceFile:39)
at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:598)
at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NullPointerException
at com.lavacraftserver.BattleKits.DeathEvent.onPlayerDeath(DeathEvent.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
... 27 more

**Comment by lol768** [comment]
You have the server enabled, right?

**Comment by lol768** [comment]
I know exactly why it is doing this :/

**Comment by lol768** [comment]
Workaround: set server.enabled to true

**Comment by xron89** [comment]
I added that but i'm still getting it spamming my console :(

**Comment by lol768** [comment]
Should hopefully be fixed in v2.0.2 - awaiting approval as of now.
